#!/usr/bin/env python3

"""Check the documentation for Sphinx errors and LaTeX build errors.

This runs ``make latexpdf-noplot`` in the ``docs`` directory,
which builds the documentation with Sphinx without running the examples,
and then builds the PDF with latexmk.
The LaTeX build directory ``_build/latex`` is removed first, as the auxiliary files of an interrupted
LaTeX build would otherwise break the next build.
The Sphinx output is saved to ``logs/sphinx_TIMESTAMP.log``
(see :py:func:`pttools.docs.setup.setup_sphinx_logging`),
followed by the console output of the build, which includes the output of the LaTeX build.
Only the Sphinx errors and warnings and the LaTeX errors are printed.
The exit code is that of ``make``.

Usage: ``uv run python -m pttools.docs.lint [--target latexpdf-noplot] [--log-dir logs]``

Run this after changing the equations in docstrings, as errors in them
break the documentation build, which uses ``--fail-on-warning``.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import time
import typing as tp

from pttools.docs.setup import SPHINX_LOG_ENV_VAR
from pttools.utils.system import PTTOOLS_DIR

REPO_DIR: str = os.path.dirname(PTTOOLS_DIR)
DOCS_DIR: str = os.path.join(REPO_DIR, "docs")
DEFAULT_LOG_DIR: str = os.path.join(REPO_DIR, "logs")
#: Path of the LaTeX build directory of the ``latexpdf`` target
LATEX_BUILD_DIR: str = os.path.join(DOCS_DIR, "_build", "latex")
#: LaTeX options, which the Makefile generated by Sphinx reads from the environment.
#: Without these, xelatex would stop at the first error and wait for input from the terminal.
DEFAULT_LATEXOPTS: str = "-interaction=nonstopmode -halt-on-error"

#: Sphinx messages of these levels are printed
SPHINX_PATTERN: re.Pattern = re.compile(r"\b(CRITICAL|SEVERE|ERROR|WARNING):")
#: Lines that indicate a TeX error, in addition to the lines that start with "!"
LATEX_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"^! "),
    re.compile(r"LaTeX Error"),
    re.compile(r"Emergency stop"),
    re.compile(r"Fatal error occurred"),
    re.compile(r"Latexmk: Errors"),
    re.compile(r"Error: Failed to run"),
    re.compile(r"Latex error"),
)
#: TeX warnings that are reported from the log of the final latexmk pass.
#: In the console output these also occur in the intermediate passes, where they are expected.
LATEX_WARNING_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"LaTeX Warning: .*(undefined|Unknown|multiply.defined)"),
    re.compile(r"There were undefined references"),
    re.compile(r"Label\(s\) may have changed"),
)
#: Lines that indicate a failure of the build tools themselves
TOOL_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"^make(\[\d+\])?: \*\*\*"),
    re.compile(r"^sphinx-build: error"),
    re.compile(r"^Traceback \(most recent call last\)"),
    re.compile(r"^Exception occurred"),
    re.compile(r"^(Sphinx|Extension|Configuration) error"),
)
#: Number of lines of the end of the output printed if make fails without a recognised error message
TAIL_LINES: int = 20
#: Number of lines of context printed after a TeX error line
LATEX_CONTEXT_LINES: int = 3
#: A line of the form "l.123 ..." ends the context of a TeX error
LATEX_LINE_PATTERN: re.Pattern = re.compile(r"^l\.\d+ ")


def split_lines(text: str) -> list[str]:
    """Split the console output into lines, including the progress lines separated by carriage returns."""
    return [line.rstrip() for line in re.split(r"\r\n|\r|\n", text)]


def sphinx_messages(lines: tp.Iterable[str]) -> list[str]:
    """Extract the Sphinx errors and warnings."""
    return [line for line in lines if SPHINX_PATTERN.search(line)]


def latex_errors(lines: tp.Sequence[str]) -> list[str]:
    """Extract the TeX errors with some lines of context."""
    found: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if any(pattern.search(line) for pattern in LATEX_PATTERNS):
            found.append(line)
            if line.startswith("!"):
                for j in range(i + 1, min(i + 1 + LATEX_CONTEXT_LINES, len(lines))):
                    found.append(lines[j])
                    if LATEX_LINE_PATTERN.match(lines[j]):
                        break
        i += 1
    return found


def tool_errors(lines: tp.Iterable[str]) -> list[str]:
    """Extract the errors of make, sphinx-build and Python itself."""
    return [line for line in lines if any(pattern.search(line) for pattern in TOOL_PATTERNS)]


def latex_log_messages(log_path: str) -> tuple[list[str], list[str]]:
    """Extract the TeX errors and warnings from the log file of the final LaTeX pass,
    e.g. ``_build/latex/pttools.log``.

    :return: error lines, warning lines
    """
    if not os.path.isfile(log_path):
        return [], []
    with open(log_path, encoding="utf-8", errors="replace") as file:
        lines = split_lines(file.read())
    warnings = [line for line in lines if any(pattern.search(line) for pattern in LATEX_WARNING_PATTERNS)]
    return latex_errors(lines), warnings


def run_make(target: str, log_path: str) -> tuple[int, list[str]]:
    """Run ``make target`` in the docs directory, streaming its output to the log file.

    :return: the return code of make and the lines of its console output
    """
    shutil.rmtree(LATEX_BUILD_DIR, ignore_errors=True)
    env = os.environ.copy()
    env[SPHINX_LOG_ENV_VAR] = log_path
    env.setdefault("LATEXOPTS", DEFAULT_LATEXOPTS)
    with subprocess.Popen(
            ["make", target],
            cwd=DOCS_DIR,
            env=env,
            # If LaTeX nevertheless asks for input, it gets an end-of-file instead of hanging.
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace") as process:
        assert process.stdout is not None
        output = process.stdout.read()
        returncode = process.wait()
    lines = split_lines(output)
    # The Sphinx process has closed the log file by now, so the console output can be appended.
    with open(log_path, "a", encoding="utf-8") as file:
        file.write(f"\n{'=' * 20} Console output of \"make {target}\" {'=' * 20}\n")
        file.write("\n".join(lines))
        file.write(f"\n{'=' * 20} make returned {returncode} {'=' * 20}\n")
    return returncode, lines


def main(argv: tp.Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target", default="latexpdf-noplot", help="the make target to run (default: %(default)s)")
    parser.add_argument("--log-dir", default=DEFAULT_LOG_DIR, help="directory for the log file (default: %(default)s)")
    args = parser.parse_args(argv)

    os.makedirs(args.log_dir, exist_ok=True)
    log_path = os.path.join(args.log_dir, f"sphinx_{time.strftime('%Y-%m-%d_%H-%M-%S')}.log")
    print(f"Running \"make {args.target}\" in {DOCS_DIR}. Log: {log_path}")
    start = time.perf_counter()
    returncode, lines = run_make(args.target, log_path)
    elapsed = time.perf_counter() - start

    sphinx_lines = sphinx_messages(lines)
    tex_lines = latex_errors(lines)
    tex_log_path = os.path.join(LATEX_BUILD_DIR, "pttools.log")
    tex_log_lines, tex_log_warnings = latex_log_messages(tex_log_path)
    if tex_lines or tex_log_lines:
        # The warnings of an aborted pass are meaningless.
        tex_log_warnings = []
    tool_lines = tool_errors(lines)

    if sphinx_lines:
        print(f"\nSphinx errors and warnings ({len(sphinx_lines)}):")
        print("\n".join(sphinx_lines))
    if tex_lines:
        print(f"\nLaTeX errors in the console output ({len(tex_lines)} lines):")
        print("\n".join(tex_lines))
    if tex_log_lines:
        print(f"\nLaTeX errors in {tex_log_path} ({len(tex_log_lines)} lines):")
        print("\n".join(tex_log_lines))
    if tex_log_warnings:
        print(f"\nLaTeX warnings in the final pass, {tex_log_path} ({len(tex_log_warnings)}):")
        print("\n".join(tex_log_warnings))
    if tool_lines:
        print(f"\nBuild tool errors ({len(tool_lines)}):")
        print("\n".join(tool_lines))
    if not (sphinx_lines or tex_lines or tex_log_lines or tex_log_warnings or tool_lines):
        if returncode:
            print(f"\nmake failed without a recognised error message. Last {TAIL_LINES} lines of the output:")
            print("\n".join(line for line in lines[-TAIL_LINES:] if line))
        else:
            print("\nNo Sphinx errors, Sphinx warnings or LaTeX errors found.")

    print(f"\nmake {args.target} returned {returncode} after {elapsed:.0f} s. Log: {log_path}")
    return returncode


if __name__ == "__main__":
    sys.exit(main())
