#!/usr/bin/env python3

"""Check the documentation for Sphinx errors and LaTeX build errors.

This runs ``make latexpdf-noplot`` in the ``docs`` directory,
which builds the documentation with Sphinx without running the examples,
and then builds the PDF with latexmk.
The LaTeX build directory ``_build/latex`` is removed first, as the auxiliary files of an interrupted
LaTeX build would otherwise break the next build.
The Sphinx output is saved to ``logs/sphinx_TIMESTAMP.log``
(see :py:func:`pttools.docs.setup.setup_sphinx_logging`, which has to be called in ``docs/conf.py``),
followed by the console output of the build, which includes the output of the LaTeX build.
Only the Sphinx errors and warnings and the LaTeX errors are printed.
The exit code is that of ``make``.

Usage: ``uv run python -m pttools.docs.lint [--target latexpdf-noplot] [--docs-dir docs] [--log-dir logs]``

This can be used also in other projects that use the documentation utilities of PTtools, such as PTPlot,
by running ``python -m pttools.docs.lint`` in their virtual environment.
The ``docs`` directory is found with :py:func:`pttools.docs.paths.find_docs_dir`:
it is looked for alongside the virtual environment (e.g. ``venv`` or ``.venv``) in which Python is running,
then as a subdirectory of the current working directory, and finally the current working directory itself
is checked. The log files are saved by default to a ``logs`` directory alongside the ``docs`` directory.

Run this after changing the equations in docstrings, as errors in them
break the documentation build, which uses ``--fail-on-warning``.
"""

import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import typing as tp

from pttools.docs.paths import default_log_dir, find_docs_dir, is_docs_dir
from pttools.docs.setup import SPHINX_LOG_ENV_VAR

#: Path of the LaTeX build directory of the ``latexpdf`` target, relative to the ``docs`` directory
LATEX_BUILD_SUBDIR: Path = Path("_build", "latex")
#: LaTeX options, which the Makefile generated by Sphinx reads from the environment.
#: Without these, xelatex would stop at the first error and wait for input from the terminal.
DEFAULT_LATEXOPTS: str = "-interaction=nonstopmode -halt-on-error"
#: The Sphinx build command, which the Makefile generated by Sphinx reads from the environment.
#: This runs Sphinx with the same Python interpreter as this script, so that the build uses
#: the virtual environment in which this script is run, even if that environment is not activated
#: and ``sphinx-build`` on ``PATH`` would be that of another environment.
DEFAULT_SPHINXBUILD: str = f"\"{sys.executable}\" -m sphinx"

#: Sphinx messages of these levels are printed
SPHINX_PATTERN: re.Pattern = re.compile(r"\b(CRITICAL|SEVERE|ERROR|WARNING):")
#: Lines that indicate a TeX error, in addition to the lines that start with "!"
LATEX_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"^! "),
    re.compile(r"LaTeX Error"),
    re.compile(r"Emergency stop"),
    re.compile(r"Fatal error occurred"),
    re.compile(r"Latexmk: Errors"),
    re.compile(r"Error: Failed to run"),
    re.compile(r"Latex error"),
)
#: TeX warnings that are reported from the log of the final latexmk pass.
#: In the console output these also occur in the intermediate passes, where they are expected.
LATEX_WARNING_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"LaTeX Warning: .*(undefined|Unknown|multiply.defined)"),
    re.compile(r"There were undefined references"),
    re.compile(r"Label\(s\) may have changed"),
)
#: Lines that indicate a failure of the build tools themselves
TOOL_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"^make(\[\d+\])?: \*\*\*"),
    re.compile(r"^sphinx-build: error"),
    re.compile(r"^Traceback \(most recent call last\)"),
    re.compile(r"^Exception occurred"),
    re.compile(r"^(Sphinx|Extension|Configuration) error"),
)
#: Number of lines of the end of the output printed if make fails without a recognised error message
TAIL_LINES: int = 20
#: Number of lines of context printed after a TeX error line
LATEX_CONTEXT_LINES: int = 3
#: A line of the form "l.123 ..." ends the context of a TeX error
LATEX_LINE_PATTERN: re.Pattern = re.compile(r"^l\.\d+ ")


def split_lines(text: str) -> list[str]:
    """Split the console output into lines, including the progress lines separated by carriage returns."""
    return [line.rstrip() for line in re.split(r"\r\n|\r|\n", text)]


def sphinx_messages(lines: tp.Iterable[str]) -> list[str]:
    """Extract the Sphinx errors and warnings."""
    return [line for line in lines if SPHINX_PATTERN.search(line)]


def latex_errors(lines: tp.Sequence[str]) -> list[str]:
    """Extract the TeX errors with some lines of context."""
    found: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if any(pattern.search(line) for pattern in LATEX_PATTERNS):
            found.append(line)
            if line.startswith("!"):
                for j in range(i + 1, min(i + 1 + LATEX_CONTEXT_LINES, len(lines))):
                    found.append(lines[j])
                    if LATEX_LINE_PATTERN.match(lines[j]):
                        break
        i += 1
    return found


def tool_errors(lines: tp.Iterable[str]) -> list[str]:
    """Extract the errors of make, sphinx-build and Python itself."""
    return [line for line in lines if any(pattern.search(line) for pattern in TOOL_PATTERNS)]


def latex_log_messages(log_path: str | os.PathLike[str]) -> tuple[list[str], list[str]]:
    """Extract the TeX errors and warnings from the log file of the final LaTeX pass,
    e.g. ``_build/latex/pttools.log``.

    :return: error lines, warning lines
    """
    log_path = Path(log_path)
    if not log_path.is_file():
        return [], []
    with log_path.open(encoding="utf-8", errors="replace") as file:
        lines = split_lines(file.read())
    warnings = [line for line in lines if any(pattern.search(line) for pattern in LATEX_WARNING_PATTERNS)]
    return latex_errors(lines), warnings


def run_make(target: str, log_path: Path, docs_dir: Path) -> tuple[int, list[str]]:
    """Run ``make target`` in the docs directory, streaming its output to the log file.

    :return: the return code of make and the lines of its console output
    """
    shutil.rmtree(docs_dir / LATEX_BUILD_SUBDIR, ignore_errors=True)
    env = os.environ.copy()
    env[SPHINX_LOG_ENV_VAR] = str(log_path)
    env.setdefault("LATEXOPTS", DEFAULT_LATEXOPTS)
    env.setdefault("SPHINXBUILD", DEFAULT_SPHINXBUILD)
    with subprocess.Popen(
            ["make", target],
            cwd=docs_dir,
            env=env,
            # If LaTeX nevertheless asks for input, it gets an end-of-file instead of hanging.
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace") as process:
        assert process.stdout is not None
        output = process.stdout.read()
        returncode = process.wait()
    lines = split_lines(output)
    # The Sphinx process has closed the log file by now, so the console output can be appended.
    with log_path.open("a", encoding="utf-8") as file:
        file.write(f"\n{'=' * 20} Console output of \"make {target}\" {'=' * 20}\n")
        file.write("\n".join(lines))
        file.write(f"\n{'=' * 20} make returned {returncode} {'=' * 20}\n")
    return returncode, lines


def resolve_docs_dir(docs_dir: str | os.PathLike[str] | None) -> Path:
    """Resolve the documentation directory given on the command line, or find it if not given.

    :raises FileNotFoundError: if the documentation directory is not found or is not valid
    """
    if docs_dir is None:
        found = find_docs_dir()
        if found is None:
            raise FileNotFoundError(
                "The documentation directory was not found alongside the virtual environment "
                f"or in the current working directory {Path.cwd()}. Specify it with --docs-dir.")
        return found
    docs_path = Path(docs_dir).resolve()
    if not is_docs_dir(docs_path):
        raise FileNotFoundError(
            f"{docs_path} is not a documentation directory, as it does not contain conf.py and Makefile.")
    return docs_path


def latex_log_paths(latex_build_dir: str | os.PathLike[str]) -> list[Path]:
    """Find the log files of the LaTeX build, e.g. ``_build/latex/pttools.log``.

    The name of the log file is that of the LaTeX document, which is configured by ``latex_documents``
    in ``conf.py`` and therefore differs between projects.
    """
    return sorted(Path(latex_build_dir).glob("*.log"))


def all_latex_log_messages(latex_build_dir: str | os.PathLike[str]) -> tuple[list[Path], list[str], list[str]]:
    """Extract the TeX errors and warnings from all the log files of the LaTeX build.

    :return: paths of the log files, error lines, warning lines
    """
    log_paths = latex_log_paths(latex_build_dir)
    errors: list[str] = []
    warnings: list[str] = []
    for log_path in log_paths:
        log_errors, log_warnings = latex_log_messages(log_path)
        errors.extend(log_errors)
        warnings.extend(log_warnings)
    return log_paths, errors, warnings


def main(argv: tp.Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target", default="latexpdf-noplot", help="the make target to run (default: %(default)s)")
    parser.add_argument(
        "--docs-dir", default=None,
        help="the documentation directory (default: found alongside the virtual environment "
             "or in the current working directory)")
    parser.add_argument(
        "--log-dir", default=None,
        help="directory for the log file (default: \"logs\" alongside the documentation directory)")
    args = parser.parse_args(argv)

    try:
        docs_dir = resolve_docs_dir(args.docs_dir)
    except FileNotFoundError as e:
        print(e, file=sys.stderr)
        return 2
    log_dir = default_log_dir(docs_dir) if args.log_dir is None else Path(args.log_dir)

    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / (f"sphinx_{time.strftime('%Y-%m-%d_%H-%M-%S')}.log")
    print(f"Running \"make {args.target}\" in {docs_dir}. Log: {log_path}")
    start = time.perf_counter()
    returncode, lines = run_make(args.target, log_path, docs_dir)
    elapsed = time.perf_counter() - start

    sphinx_lines = sphinx_messages(lines)
    tex_lines = latex_errors(lines)
    tex_log_paths, tex_log_lines, tex_log_warnings = all_latex_log_messages(docs_dir / LATEX_BUILD_SUBDIR)
    tex_log_str = ", ".join(str(path) for path in tex_log_paths)
    if tex_lines or tex_log_lines:
        # The warnings of an aborted pass are meaningless.
        tex_log_warnings = []
    tool_lines = tool_errors(lines)

    if sphinx_lines:
        print(f"\nSphinx errors and warnings ({len(sphinx_lines)}):")
        print("\n".join(sphinx_lines))
    if tex_lines:
        print(f"\nLaTeX errors in the console output ({len(tex_lines)} lines):")
        print("\n".join(tex_lines))
    if tex_log_lines:
        print(f"\nLaTeX errors in {tex_log_str} ({len(tex_log_lines)} lines):")
        print("\n".join(tex_log_lines))
    if tex_log_warnings:
        print(f"\nLaTeX warnings in the final pass, {tex_log_str} ({len(tex_log_warnings)}):")
        print("\n".join(tex_log_warnings))
    if tool_lines:
        print(f"\nBuild tool errors ({len(tool_lines)}):")
        print("\n".join(tool_lines))
    if not (sphinx_lines or tex_lines or tex_log_lines or tex_log_warnings or tool_lines):
        if returncode:
            print(f"\nmake failed without a recognised error message. Last {TAIL_LINES} lines of the output:")
            print("\n".join(line for line in lines[-TAIL_LINES:] if line))
        else:
            print("\nNo Sphinx errors, Sphinx warnings or LaTeX errors found.")

    print(f"\nmake {args.target} returned {returncode} after {elapsed:.0f} s. Log: {log_path}")
    return returncode


if __name__ == "__main__":
    sys.exit(main())
