pipelines:
  default:
    - parallel:
      - step:
          name: Lint
          image: python:3.8
          caches:
            - pip
          script:
            - python -V
            - pip install -r requirements.txt
            - pip install pylint
            - pylint . bubble gw_code tests 2>&1 | tee pylint.txt
          artifacts:
            - pylint.txt
      - step:
          name: Graph
          image: python:3.8
          caches:
            - pip
          script:
            - python -V
            - apt-get update
            - apt-get install -y graphviz
            - pip install -r requirements.txt
            - pip install pylint
            - pyreverse . -o png
            - pyreverse . -o svg
          artifacts:
            - classes.png
            - classes.svg
            - packages.png
            - packages.svg
      - step:
          name: Test
          image: python:3.8
          caches:
            - pip
          script:
            - python -V
            - pip install -r requirements.txt
            - pip install coverage
            - coverage run
            # - coverage combine
            - coverage report | tee coverage.txt
            - coverage html
            - coverage xml
            - coverage json
            - bash <(curl -s https://codecov.io/bash)
          artifacts:
            - coverage.txt
            - coverage.xml
            - coverage.json
            - htmlcov
      - step:
          name: Test with Python 3.6
          image: python:3.6
          caches:
            - pip
          script:
            - python -V
            - pip install -r requirements.txt
            - pip install coverage
            - coverage run
