# Anaconda environment configuration for testing with old library versions

name: pttools
dependencies:
  - python == 3.7
  - llvmlite == 0.29.0
  - matplotlib
  - numba == 0.45.1
  - numpy == 1.19.0
  - plotly
  - scipy
  - tbb
