# Anaconda environment configuration

# Create the environment with:
# conda env create --name pttools --file environment.yml
# Activate the environment with:
# conda activate pttools

# If you get an error with the following lines in its long output:
# Fatal Python error: Aborted
# File "pttools/envs/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 119 in _create_qApp
# Then run the following commands:
# conda uninstall pyqt
# conda install matplotlib-base

name: pttools
channels:
  - conda-forge
  - defaults
  # - numba
  # - nvidia
dependencies:
  # The Python version is currently constrained by the NumbaLSODA package.
  # Once it becomes compatible with newer Python, update this to the latest version.
  # https://anaconda.org/channels/conda-forge/packages/python/overview
  - python == 3.14.3
  # -----
  # Mandatory dependencies
  # -----
  # https://anaconda.org/channels/conda-forge/packages/h5py/overview
  - h5py == 3.15.1
  # https://anaconda.org/channels/conda-forge/packages/h5py/overview
  - matplotlib == 3.10.8
  # https://anaconda.org/channels/conda-forge/packages/numba/overview
  - numba == 0.64.0
  # https://anaconda.org/channels/conda-forge/packages/numpy/overview
  - numpy == 2.4.2
  # https://anaconda.org/channels/conda-forge/packages/orjson/overview
  - orjson == 3.11.7
  # https://anaconda.org/channels/conda-forge/packages/pip/overview
  - pip == 26.0.1
  # https://anaconda.org/channels/conda-forge/packages/plotly/overview
  - plotly == 6.5.0
  # https://anaconda.org/channels/conda-forge/packages/python-kaleido/overview
  - python-kaleido == 0.2.1
  # https://anaconda.org/channels/conda-forge/packages/scipy/overview
  - scipy == 1.17.0
  # -----
  # Optional dependencies
  # -----
  # Intel SVML for Numba
  # https://anaconda.org/channels/conda-forge/packages/intel-cmplr-lib-rt/overview
  # https://numba.readthedocs.io/en/stable/user/performance-tips.html#intel-svml
  - intel-cmplr-lib-rt >= 2025.3.2
  # Numbalsoda
  # The conda package requires Python <= 3.11
  # https://anaconda.org/channels/conda-forge/packages/numbalsoda/overview
  # - numbalsoda == 0.3.5
  # https://anaconda.org/channels/conda-forge/packages/tbb/overview
  - tbb >= 2022.3.0
  # -----
  # Development dependencies
  # -----
  # https://anaconda.org/channels/conda-forge/packages/allure-pytest/overview
  - allure-pytest == 2.15.3
  # https://anaconda.org/channels/conda-forge/packages/python-build/overview
  - python-build == 1.4.0
  # https://anaconda.org/channels/conda-forge/packages/colorama/overview
  - colorama == 0.4.6
  # https://anaconda.org/channels/conda-forge/packages/pandas/overview
  - pandas == 3.0.1
  # https://anaconda.org/channels/conda-forge/packages/psutil/overview
  - psutil == 7.2.2
  # https://anaconda.org/channels/conda-forge/packages/pyan3/overview
  - pyan3 == 2.0.0
  # https://anaconda.org/channels/conda-forge/packages/pyinstrument/overview
  - pyinstrument == 5.1.2
  # https://anaconda.org/channels/conda-forge/packages/pylint/overview
  - pylint == 4.0.5
  # https://anaconda.org/conda-forge/pytest
  - pytest == 9.0.2
  # https://anaconda.org/channels/conda-forge/packages/pytest-cov/overview
  - pytest-cov == 7.0.0
  # https://anaconda.org/channels/conda-forge/packages/pytest-html/overview
  - pytest-html == 4.2.0
  # https://anaconda.org/channels/conda-forge/packages/pytest-xdist/overview
  - pytest-xdist == 3.8.0
  # https://anaconda.org/channels/conda-forge/packages/setuptools/overview
  - setuptools == 82.0.0
  # https://anaconda.org/channels/conda-forge/packages/twine/overview
  - twine == 6.2.0
  # https://anaconda.org/channels/conda-forge/packages/wheel/overview
  - wheel == 0.46.3
  # https://anaconda.org/channels/conda-forge/packages/yappi/overview
  - yappi == 1.7.3
  # -----
  # Pip packages
  # -----
  - pip:
    # https://pypi.org/project/numbalsoda/
    - numbalsoda == 0.3.4
