[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "pttools-gw"
version = "0.10.0"
description = "PTtools simulation framework for phase transitions in the early universe"
readme = "README.md"
# PTtools is licensed under the MIT License in accordance with the University of Helsinki recommendations.
# https://www.helsinki.fi/en/helsinki-university-library/library-researchers/copyright-and-licenses
# "We primarily recommend the MIT licence."
# https://blogs.helsinki.fi/thinkopen/open-source-at-the-university-of-helsinki/
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "cosmology",
    "phase transitions",
    "gravitational waves",
    "hydrodynamics",
    "relativistic hydrodynamics",
    "sound shell model"
]
# When updating these, also update acknowledgements.rst, AUTHORS, CITATION.cff and codemeta.json
authors = [
    {name = "Mark Hindmarsh", email = "mark.hindmarsh@helsinki.fi"},
    {name = "Chloe Hopling", email = "c.hopling@sussex.ac.uk"},
    {name = "Mika Mäki", email = "mika.x.maki@helsinki.fi"},
    {name = "Lorenzo Giombi", email = "lorenzo.giombi@helsinki.fi"}
]
maintainers = [
    {name = "Mark Hindmarsh", email = "mark.hindmarsh@helsinki.fi"},
    {name = "Mika Mäki", email = "mika.x.maki@helsinki.fi"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Matplotlib",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: OS Independent",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Free Threading :: 1 - Unstable",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]
# When updating these, also update environment.yml and requirements.txt.
# Please also ensure that compatible versions are available in LISA ProtoLab.
dependencies = [
    "h5py >= 3.16.0",
    "kaleido >= 1.3.0",
    "matplotlib >= 3.10.9",
    "numba >= 0.65.1",
    "numpy >= 2.4.6",
    "orjson >= 3.11.9",
    "plotly >= 6.6.0",
    "scipy >= 1.17.1",
]
# Note: LISA ProtoLab uses Python 3.13, and PTtools should therefore probably stay compliant with it.
# https://gitlab.esa.int/mika.x.maki/lisa-protolab
requires-python = ">= 3.12"
# dynamic = ["version"]

[project.optional-dependencies]
numbalsoda = ["numbalsoda >= 0.3.4"]
performance = [
    "icc-rt >= 2019.0; platform_machine != 'arm64' and sys_platform == 'darwin'",
    "intel-cmplr-lib-rt >= 2025.3.3; platform_machine != 'arm64' and sys_platform != 'darwin'",
    "intel-openmp >= 2023.2.0; platform_machine != 'arm64' and sys_platform == 'darwin'",
    "tbb >= 2021.10.0; platform_machine != 'arm64'",
]

[project.urls]
documentation = "https://pttools.readthedocs.io"
issues = "https://github.com/CFT-HY/pttools/issues"
repository = "https://github.com/CFT-HY/pttools"

[tool.coverage.run]
branch = true
# command_line = "manage.py test --noinput --parallel"
concurrency = [
    "thread",
    "multiprocessing"
]
source = ["."]
omit = [
    "**/envs/*",
    "**/venv/*"
]
parallel = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "if __name__ == .__main__.:"
]
show_missing = true

[tool.mypy]
exclude = [
    "_build",
    "auto_examples"
]
files = [
    "docs",
    "examples",
    "pttools",
    "tests"
]

[[tool.mypy.overrides]]
module = ["h5py.*", "numba.*", "numbalsoda.*", "plotly.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
# On clusters "--numprocesses=auto" creates processes according to the total number of CPU cores
# instead of the number of cores available to the job.
# Therefore, it may be wise to set the number of processes manually.
addopts = [
    "--alluredir=test-results/allure",
    "--cov=.",
    "--cov-report=html",
    "--cov-report=term",
    "--cov-report=term-missing",
    "--cov-report=xml",
    "--dist=loadscope",
    "--html=test-results/html/test-report.html",
    "--numprocesses=auto"
]
norecursedirs = "test_data"
# python_paths = "tests"
testpaths = [
    "tests"
]
# log_cli = true
# log_cli_level = "INFO"

# [tool.setuptools.dynamic]
# version = {attr = "docs.conf.version"}

[tool.setuptools.packages.find]
include = [
    "pttools*",
]
exclude = [
    "docs",
    "examples",
    "htmlcov",
    "logs",
    "test-results",
    "tests",
    "venv"
]
