"""
Model from data
===============

Create an equation of state model from an HDF5 data file generated by e.g. WallGo.
The data used in this example have been generated with this script:
https://github.com/Wall-Go/WallGo/blob/main/Models/SingletStandardModel_Z2/exampleOutputThermodynamics.py

Todo: This example is preliminary, and the solvers don't yet work properly for the model in the WallGo example file.
"""

import logging
import os.path

import matplotlib.pyplot as plt

from pttools.bubble import Bubble
from pttools.models import DataModel
# from pttools.analysis.plot_model import ModelPlot

logger = logging.getLogger(__name__)


def main(data_path: str = "thermodynamics_data.h5"):
    """Plot a bubble using a DataModel from an HDF5 data file"""
    # __file__ is not supported for example files by sphinx-gallery
    if not os.path.isfile(data_path):
        print("The data file was not found. Please generate it and place in the current directory.")
        return
    model = DataModel.from_hdf5(data_path)
    print(model.info())

    # fig = plt.figure()
    # ax = fig.add_subplot()
    # plot = ModelPlot(model)

    try:
        bubble = Bubble(model, v_wall=0.5, alpha_n=0.1)
        bubble.plot()
    except RuntimeError as e:
        logger.exception("Failed to create a bubble using DataModel.", exc_info=e)


if __name__ == "__main__":
    main()
    plt.show()
