name: Publish
on:
  release:
    types: [published, created, edited]
  workflow_dispatch:
jobs:
  deploy-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Print Python version
        run: python -V
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load pip cache
        uses: actions/cache@v2
        with:
          path: .pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
            pip-
      - name: Install requirements
        run: |
          pip --cache-dir=.pip install --upgrade pip
          pip --cache-dir=.pip install build twine
      - name: Build
        run: python -m build
      - name: Run Twine checks
        run: twine check dist/*
      - name: Upload built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pip packages
          path: dist
          if-no-files-found: error
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
