name: Publish Docker image
on:
  release:
    types: [published]
  workflow_run:
    workflows: [CI]
    types: [completed]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    uses: docker/github-builder/.github/workflows/build.yml@v1
    environment: Deploy
    # Allow running when the CI pipeline succeeded or when the workflow is triggered manually
    if: ${{ github.event.release.tag_name != '' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    with:
      cache: true
      meta-images: |
        ghcr.io/${{ github.repository }}
        cfthy/pttools
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      sbom: true
      set-meta-labels: true
      secrets:
        registry-auths: |
          - registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
          - registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
