name: Publish to Software Heritage Foundation
on:
  release:
    types: [published, created, edited]
  workflow_dispatch:
jobs:
  deploy-shf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # https://github.com/marketplace/actions/save-to-software-heritage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish to Software Heritage Foundation
        uses: sdruskat/swh-save-action@v1.0.1
