name: Publish PyPI package
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
env:
  PYTHON_VERSION: '3.14'
jobs:
  deploy-pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # https://github.com/marketplace/actions/pypi-publish
    environment:
      name: pypi
      url: https://pypi.org/p/pttools-gw
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup uv
        uses: astral-sh/setup-uv@v10
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Print Python version
        run: uv python find --show-version
      - name: Build
        run: uv build
      - name: Run Twine checks
        run: uvx twine check dist/*
      - name: Upload built artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Python packages
          path: dist
          if-no-files-found: error
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # An API token is not needed with trusted publishing (OpenID Connect)
        # with:
        #   user: __token__
        #   password: ${{ secrets.PYPI_API_TOKEN }}
