name: Docs
on: push
permissions:
  contents: read
jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          activate-environment: true
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y cm-super dvipng ffmpeg fontconfig graphviz latexmk optipng texlive-latex-extra texlive-xetex fonts-freefont-otf xindy
      - name: Install requirements
        run: uv sync --locked --all-extras
      - name: Print Python version
        run: python -V
      - name: Generate reference data
        run: python pttools/bubble/fluid_reference.py
        env:
          PYTHONPATH: .
      - name: Generate documentation
        run: |
          cd docs
          make all
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: Documentation
          path: |
            docs/_build
          if-no-files-found: error
