name: Docs
on: push
permissions:
  contents: read
jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          activate-environment: true
      - name: Print uv and Python versions
        run: |
          echo "uv ${UV_VERSION}"
          echo "Python ${PYTHON_VERSION}"
        env:
          UV_VERSION: ${{ steps.setup-uv.outputs.uv-version }}
          PYTHON_VERSION: ${{ steps.setup-uv.outputs.python-version }}
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y cloc cm-super dvipng ffmpeg fontconfig graphviz latexmk optipng texlive-latex-extra texlive-xetex fonts-freefont-otf xindy
      - name: Install requirements
        run: uv sync --locked --all-extras
      - name: Check TBB
        run: python -c "from pttools.speedup import tbb; import sys; v = tbb.load_tbb(); print('TBB version:', v); sys.exit(v is None or v < tbb.TBB_MIN_VERSION)"
      - name: Generate reference data
        run: python pttools/bubble/fluid_reference.py
        env:
          PYTHONPATH: .
      - name: Generate documentation
        run: make -C docs all
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: Documentation
          path: |
            docs/_build
          if-no-files-found: error
