name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Print Python version
        run: python -V
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load pip cache
        uses: actions/cache@v2
        with:
          path: .pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
            pip-
      - name: Install requirements
        run: |
          pip --cache-dir=.pip install --upgrade pip
          pip --cache-dir=.pip install pylint
          pip --cache-dir=.pip install -r requirements.txt
      - name: Run Pylint
        run: pylint . bubble gw_code tests 2>&1 | tee pylint.txt
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Lint
          path: |
            ${{ github.workspace }}/pylint.txt
          if-no-files-found: error
  graph:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Print Python version
        run: python -V
      - name: Install graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load pip cache
        uses: actions/cache@v2
        with:
          path: .pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
            pip-
      - name: Install requirements
        run: |
          pip --cache-dir=.pip install --upgrade pip
          pip --cache-dir=.pip install pylint
          pip --cache-dir=.pip install -r requirements.txt
      - name: Run Pyreverse
        run: |
          pyreverse . -o png
          pyreverse . -o svg
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Graph
          path: |
            classes.png
            classes.svg
            packages.png
            packages.svg
          if-no-files-found: error
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print Python version
      run: python -V
    - name: Checkout
      uses: actions/checkout@v2
    - name: Load pip cache
      uses: actions/cache@v2
      with:
        path: .pip
        key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-
          pip-
    - name: Install requirements
      run: |
        pip --cache-dir=.pip install --upgrade pip
        pip --cache-dir=.pip install coverage
        pip --cache-dir=.pip install -r requirements.txt
    - name: Run tests with coverage
      run: coverage run
    - name: Create coverage reports
      run: |
        coverage report | tee coverage.txt
        coverage html
        coverage xml
        coverage json
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: Coverage
        path: |
          coverage.txt
          coverage.xml
          coverage.json
          htmlcov
        if-no-files-found: error
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v1
      if: ${{ matrix.python-version }} == "3.8"
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ${{ github.workspace }}/coverage.xml
